import type { Product } from "./api/types/product";

export const testProducts: Product[] = [
  {
    id: 1,
    name: 'Test Product 1',
    subName: 'SubName 1',
    description: 'Description for product 1',
    images: [],
    price: 99.99,
    quantity: 10,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 2,
    name: 'Test Product 2',
    subName: 'SubName 2',
    description: 'Description for product 2',
    images: [],
    price: 149.99,
    quantity: 5,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 3,
    name: 'Test Product 3',
    subName: 'SubName 3',
    description: 'Description for product 3',
    images: [],
    price: 249.99,
    quantity: 1,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 4,
    name: 'Test Product 4',
    subName: 'SubName 4',
    description: 'Description for product 4',
    images: [],
    price: 302.99,
    quantity: 29,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 5,
    name: 'Test Product 5',
    subName: 'SubName 5',
    description: 'Description for product 5',
    images: [],
    price: 26.99,
    quantity: 100,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 5,
    name: 'Test Product 5',
    subName: 'SubName 5',
    description: 'Description for product 5',
    images: [],
    price: 47.99,
    quantity: 25,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 6,
    name: 'Test Product 6',
    subName: 'SubName 6',
    description: 'Description for product 6',
    images: [],
    price: 100.99,
    quantity: 43,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 7,
    name: 'Test Product 7',
    subName: 'SubName 7',
    description: 'Description for product 7',
    images: [],
    price: 27.99,
    quantity: 21,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 8,
    name: 'Test Product 8',
    subName: 'SubName 8',
    description: 'Description for product 8',
    images: [],
    price: 21.99,
    quantity: 27,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
  {
    id: 9,
    name: 'Test Product 9',
    subName: 'SubName 9',
    description: 'Description for product 9',
    images: [],
    price: 109.99,
    quantity: 27,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
{
    id: 10,
    name: 'Test Product 10',
    subName: 'SubName 10',
    description: 'Description for product 10',
    images: [],
    price: 125.99,
    quantity: 11,
    badges: [],
    groups: [],
    createdDate: new Date(),
    updatedDate: new Date(),
  },
];